[package]
name = "wasm-mima"
version = "0.1.1"
edition = "2021"
authors = ["Yannis Storrer"]
license = "GPL-3.0"
description = "Web Assembly API for the MIMA Cpu."

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
